# Generated by Django 3.0.7 on 2020-06-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_title',
            new_name='title',
        ),
    ]
